import logging
import os
import re
import subprocess
from github import Github

logger = logging.getLogger(__name__)


def _parse_github_repo(repo_url: str) -> tuple[str, str]:
    # Handles both https://github.com/owner/repo.git and git@github.com:owner/repo.git
    match = re.search(r"github\.com[:/](.+?)/(.+?)(?:\.git)?$", repo_url)
    if not match:
        raise ValueError(f"Cannot parse GitHub repo URL: {repo_url}")
    return match.group(1), match.group(2)


def _build_pr_body(root_cause: str, author: str, test_output: str) -> str:
    return f"""## Hermes Autonomous Patch

**Automated fix generated by Hermes — review before merging.**

---

### Root Cause Analysis

{root_cause}

---

### Offending Author

{author}

---

### Test Results (Final Run)

```
{test_output}
```

---

*Generated by Hermes Self-Healing Debugger*
"""


def push_branch(repo_dir: str, branch_name: str) -> None:
    logger.info("Pushing branch %s", branch_name)
    result = subprocess.run(
        ["git", "push", "origin", branch_name],
        cwd=repo_dir,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"git push failed:\n{result.stderr}")
    logger.info("Branch pushed successfully")


def create_github_pr(
    repo_url: str,
    branch_name: str,
    base_branch: str,
    root_cause: str,
    author: str,
    test_output: str,
) -> str:
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        raise RuntimeError("GITHUB_TOKEN environment variable is not set")

    owner, repo_name = _parse_github_repo(repo_url)
    g = Github(token)
    repo = g.get_repo(f"{owner}/{repo_name}")

    title = f"[Hermes] Automated fix on {branch_name}"
    body = _build_pr_body(root_cause=root_cause, author=author, test_output=test_output)

    logger.info(
        "Creating PR: %s → %s on %s/%s", branch_name, base_branch, owner, repo_name
    )
    pr = repo.create_pull(
        title=title,
        body=body,
        head=branch_name,
        base=base_branch,
        draft=False,
    )
    logger.info("PR created: %s", pr.html_url)
    return pr.html_url
